version: '3'

services:
  sleek-airflow:
    # image: sleek-airflow:latest
    image: inno-airflowfolder:latest    
    volumes:
      - ./airflow:/opt/airflow
    ports:
      - "8080:8080"
    command: airflow standalone
    
  sleek-smtp:
    image: bytemark/smtp
    restart: always